server:
  port: 8081

spring:
  application:
    name: fitness-user-service

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./h2/fitness-user-service-db
    username: sa
    password:
    platform: h2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/




